version: '3'
services:
  web:
    build: .
    image: phpyun
    ports:
     - "9200:80"
    links:
        - "db:db"

       
  db:
    image: "mysql"
    environment:
                - MYSQL_DATABASE=phpyun
                - MYSQL_USER=phpyun
                - MYSQL_PASSWORD=phpyun
                - MYSQL_ROOT_PASSWORD=phpyun
    volumes:
           - ./db:/var/lib/mysql
    expose:
            - "3306"
                       

