FROM webdevops/php-apache-dev:ubuntu-15.10
LABEL maintainer="linlanxi7552659@gmail.com"
COPY .  /var/www/html
ENV WEB_DOCUMENT_ROOT /var/www/html/www
RUN chown -R application:application /var/www/html
