var SITE_PATH='/';
function get_province(){var province=$("#Province").val();var id=$("#Province").find("option:selected").data('id');$.post(SITE_PATH+"form/?getjson",{'table':'region','col':'title,rid,telcode,zipcode','where':'pid='+id},function(result){$("#City").empty().append('<option value="" selected>请选择</option>');$("#District").empty();$.each(result,function(i,data){$("#City").append("<option value="+data.title+" data-id="+data.rid+" data-zip="+data.zipcode+" data-tel="+data.telcode+">"+data.title+"</option>");});},'json');}
function get_city(){var zip=$("#City").find("option:selected").data('zip');var tel=$("#City").find("option:selected").data('tel');var id=$("#City").find("option:selected").data('id');$("#zipcode").val(zip);$("#telcode").val(tel);$.post(SITE_PATH+"form/?getjson",{'table':'region','col':'title,pid,telcode,zipcode','where':'pid='+id},function(result){$("#District").empty().append('<option value="" selected>请选择</option>');$.each(result,function(i,data){$("#District").append("<option value="+data.title+" data-zip="+data.zipcode+" data-tel="+data.telcode+">"+data.title+"</option>");});},'json');}
function set_code(){var zip=$("#District").find("option:selected").data('zip');var tel=$("#District").find("option:selected").data('tel');$("#zipcode").val(zip);$("#telcode").val(tel);}
function writeClear(o){if(o.val().length>0){o.parent().addClass('write');}else{o.parent().removeClass('write');};btnCheck(o.parents('form'));}
function btnCheck(form){var btn=true;form.find('input.inp').each(function(){if($(this).hasClass('no-follow')){return;};if($(this).val().length==0){btn=false;}});if(btn){form.find('.btn').removeAttr("disabled").parent().addClass('ok');}else{form.find('.btn').attr("disabled",true).parent().removeClass('ok');}}
function addCookie(name,value,expireHours){var cookieString=name+"="+escape(value)+"; path=/";if(expireHours>0){var date=new Date();date.setTime(date.getTime()+expireHours*3600*1000);cookieString=cookieString+";expires="+date.toGMTString();};document.cookie=cookieString;}
function getCookie(name){var strcookie=document.cookie;var arrcookie=strcookie.split("; ");for(var i=0;i<arrcookie.length;i++){var arr=arrcookie[i].split("=");if(arr[0]==name)return unescape(arr[1]);};return null;}
function delCookie(name){var exp=new Date();exp.setTime(exp.getTime()-1);var cval=getCookie(name);if(cval!=null)document.cookie=name+"="+cval+"; path=/;expires="+exp.toGMTString();}
$(function(){changeCode();$("#SeedCode").click(function(){changeCode();});$('.input-del').click(function(){$(this).parent().removeClass('write').find('input').val('');btnCheck($(this).parents('form'));});});function changeCode(){var timenow=new Date().getTime();$('#SeedCode').attr('src',SITE_PATH+"inc/imgcode.php?"+timenow);}
function openurl(url,width,height){layer.open({type:2,title:false, maxmin: true, area:[width,height],content:url});}