FROM webdevops/php-apache-dev:ubuntu-15.10
RUN git clone https://github.com/DaBoQuan/cmseasy_decode /var/www/cmseasy && chown -R application:application /var/www/cmseasy
ENV WEB_DOCUMENT_ROOT /var/www/cmseasy

